name: Build and deploy containers

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
      build-images:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
#
#          - name: Set up Docker Context for Buildx
#            id: buildx-context
#            run: |
#              docker context create builders
#
#          - name: Set up Docker Buildx
#            id: buildx
#            uses: docker/setup-buildx-action@v2
#            with:
#              endpoint: builders

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build images'
            run: |
              docker build suse_leap_arc --tag ghcr.io/aard-fi/leap_arc:latest
              docker push ghcr.io/aard-fi/leap_arc:latest
